# Generated by Django 4.2 on 2023-05-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requesttext', models.TextField()),
                ('DateTimeField', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('Messanger', models.CharField(default='telegram', max_length=20)),
            ],
        ),
    ]
