# Generated by Django 4.2 on 2023-05-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLinkToId',
            fields=[
                ('lschet', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('id', models.IntegerField()),
                ('current', models.BooleanField()),
                ('datetimelastmesg', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('NumTreeMesg', models.IntegerField(default=0)),
            ],
        ),
    ]
